# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 21:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newrelic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_key',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_key', to=settings.AUTH_USER_MODEL),
        ),
    ]
